const products = [
    {
        productName: "Kwun-B33H",
        productModel:"Kwun-B33H",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png"},
        ],
        productVideo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B33H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B33H.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B33H.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B33H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B33H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B33H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B33H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B33H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B33H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B33H.lifeAndEndurance.warrantyPeriod"},
            ],
        },
    },
    {
        productName: "Kwun-B32H",
        productModel:"Kwun-B32H",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B32H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B32H.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B32H.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B32H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B32H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B32H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B32H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B32H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B32H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B32H.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],

        },
    },
    {
        productName: "Kwun-B32L",
        productModel:"Kwun-B32L",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/02.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/03.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/04.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/05.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/33/bg-white/06.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B32L.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B32L.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B32L.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B32L.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B32L.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B32L.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B32L.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B32L.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B32L.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B32L.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B32L.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B32L.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B22H",
        productModel:"Kwun-B22H",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B22H.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B22H.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B22H.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B22H.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B22H.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B22H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B22H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B22H.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B22L",
        productModel:"Kwun-B22L",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/01.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/2.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/3.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/4.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/5.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/22/bg-white/6.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B22L.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B22L.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B22L.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B22L.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B22L.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B22H.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B22H.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B22H.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B22H.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B22H.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
    {
        productName: "Kwun-B11L",
        productModel:"Kwun-B11L",
        price:138888,
        productImgList:[
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/1.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/1.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/2.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/2.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/3.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/3.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/4.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/4.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/5.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/5.png"},
            {swiperImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/6.png",
                dotImg: "https://file.kwunphi.com/kwunphi4/images/kwun/11/bg-white/6.png"},
        ],
        videoInfo:{
            coverImgUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-cover-B11L.jpg",
            videoUrl:"https://file.kwunphi.com/kwunphi4/videos/product/product-video-B11L.mp4",
        },
        productSpecifications:{
            productTitle: "productSpecs.Kwun-B11L.productVersion",
            Specifications:[
                {name:"productSpecs.shape.specs.bodySizeWithoutRoller",value:"productSpecs.Kwun-B11L.shape.bodySizeWithoutRoller"},
                {name:"productSpecs.shape.specs.rollerWeightDetachable",value:"productSpecs.Kwun-B11L.shape.bodyWeightWithoutRoller"},
                {name:"productSpecs.abilityToClean.specs.cleaningEfficiency",value:"productSpecs.Kwun-B11L.abilityToClean.cleaningEfficiency"},
                {name:"productSpecs.lifeAndEndurance.specs.enduranceTime",value:"productSpecs.Kwun-B11L.lifeAndEndurance.enduranceTime"},
                {name:"productSpecs.lifeAndEndurance.specs.chargingTime",value:"productSpecs.Kwun-B11L.lifeAndEndurance.chargingTime"},
                {name:"productSpecs.standardParameters.specs.dryPVPanelAngle",value:"productSpecs.Kwun-B11L.standardParameters.dryPVPanelAngle"},
                {name:"productSpecs.standardParameters.specs.wetPVPanelAngle",value:"productSpecs.Kwun-B11L.standardParameters.wetPVPanelAngle"},
                {name:"productSpecs.lifeAndEndurance.specs.designLife",value:"productSpecs.Kwun-B11L.lifeAndEndurance.designLife"},
                {name:"productSpecs.lifeAndEndurance.specs.warrantyPeriod",value:"productSpecs.Kwun-B11L.lifeAndEndurance.warrantyPeriod"},
            ],
            equipmentPackage:[],
            accessories:[],
        },
    },
]
