<template>
  <div class="container">
    <nav-header :title="$t('foot.maintenance')"></nav-header>
    <div class="maintenance-container">
      <div class="maintenance-item-container">

        <div class="desc-container">
          <h1>{{ $t('maintenance.kwunMaintenance') }}</h1>
          <p>{{ $t('maintenance.desc.desc0') }}</p>
          <p>{{ $t('maintenance.desc.desc1') }}</p>
          <p>{{ $t('maintenance.desc.desc2') }}</p>
          <p>{{ $t('maintenance.desc.desc3') }}</p>
          <p>{{ $t('maintenance.desc.desc4') }}</p>
          <p>{{ $t('maintenance.desc.desc5') }}</p>
          <span>{{ $t('maintenance.desc.desc6') }}</span>
        </div>
        <div class="maintenance-swiper-container">
            <div class="maintenance-parts-name-container">
              <div class="parts-name-container header-nav">
                <h1>{{currentServiceType}}</h1>
              </div>
              <div v-for="(serviceTypeItem,SIndex) in serviceTypeList" class="part-item-container"
                   :class="{'first-child':SIndex===0}">
                <div class="parts-name-container"><h1>{{serviceTypeItem.title}}</h1></div>
                <div v-for="(partItem,PIndex) in serviceTypeItem.list" class="part-item">
                  <div class="name-container">
                    <p>{{partItem.partName}}</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="type-drawer-container">
              <div class="parts-support-container">
                <div class="maintenance-type-container">
                  <div v-for="(levelItem,levelIndex) in levelList" class="type-container">
                    <div class="type-content">
                      <h2>{{levelItem.title}} {{currencyFilter.get(levelItem.currency).icon}}{{levelItem.price}}</h2>
                      <div class="type-item-container">
                        <div v-for="(typeI,TIndex) in typeItem" class="type-item">
                          <p>{{typeI.title}}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div v-for="(serviceTypeItem,SIndex) in serviceTypeList" class="part-item-container" :class="{'first-child':SIndex===0}">
                  <div class="parts-name-container"><h1 style="opacity: 0">{{serviceTypeItem.title}}</h1></div>
                  <div v-for="(partItem,PIndex) in serviceTypeItem.list" class="part-item">
                    <div v-for="(maintenanceLevel,LIndex) in partItem.maintenanceLevel" class="type-container partItemType">
                      <div v-for="(supportItem,SuIndex) in maintenanceLevel.category" class="support-item">
                        <img :src="supportItem.isSupport? 'https://file.kwunphi.com/kwunphi4/images/commons/right-round.svg':'https://file.kwunphi.com/kwunphi4/images/icon/false-line.svg'">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { useI18n } from "vue-i18n";
const { t, locale } = useI18n()
useHead({
  title: t('foot.maintenance'),
  meta: [
    {name: 'keywords', content: t('seo.pages.maintenance.keywords') },
    {name: 'description', content: t('seo.pages.maintenance.description') }
  ],
})
const containers = ref([]);
function handleEnter(title){
  currentServiceType.value=title
}

const partsList = ref([
  {
    partName:t("maintenance.aiModuleAssembly"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.bspUnitDriverModule"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.visualLocalizationModule"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.rollingBrushMotorDriverModule"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.suctionAssembly"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.startButton"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.radiator"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.powerModuleAssembly"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.communicationModuleAssembly"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.powerTrainAssembly"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.suctionSteeringAssembly"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.servoMotor"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.casing"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.chassis"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.logoPlate"),
    partType:1,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.batteryExplosionProofCasing"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.batteryHandle"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.deviceBatteryTopCover"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.caterpillarTrack"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.driveWheel"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.idlerWheel"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.synchronousWheel"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.synchronousWheelLockingPlate"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.wheelAxle"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.bristleBrush"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.rollerBrushBracket"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.rollerBrushMotor"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.suctionCup"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.dustCover"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.airFilter"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.airFilterElement"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.lightBarrierBrush"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.waterSprayNozzle"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.overcurrentPipeline"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.nozzleBracket"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.rotaryPlatformAssembly"),
    partType:2,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:true,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.tianyunOSOperatingSystem"),
    partType:3,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.ai-KwunOperatingSoftware"),
    partType:3,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.bspUnitFirmware"),
    partType:3,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:false,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:true,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.wholeDeviceBeautification"),
    partType:4,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.positioningCorrection"),
    partType:4,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
  {
    partName:t("maintenance.cleaningForceCalibration"),
    partType:4,
    maintenanceLevel:[
      {
        level:1,
        price:1500,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:2,
        price:2800,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
      {
        level:1,
        price:4900,
        currency:1,
        category:[
          {
            categoryId:1,
            categoryName:t("maintenance.maintenanceTitle"),
            isSupport:true,
          },
          {
            categoryId:2,
            categoryName:t("maintenance.repair"),
            isSupport:false,
          },
          {
            categoryId:3,
            categoryName:t("maintenance.replacement"),
            isSupport:false,
          },
        ]
      },
    ]
  },
])
// 过滤出 partType 为 1 的项
const filteredItems1 = computed(() => {
  return partsList.value.filter(part => part.partType === 1);
});
const filteredItems2 = computed(() => {
  return partsList.value.filter(part => part.partType === 2);
});
const filteredItems3 = computed(() => {
  return partsList.value.filter(part => part.partType === 3);
});
const filteredItems4 = computed(() => {
  return partsList.value.filter(part => part.partType === 4);
});

const serviceTypeList = ref([
  {title:t("maintenance.wearResistantParts"),list:filteredItems1.value},
  {title:t("maintenance.consumableParts"),list:filteredItems2.value},
  {title:t("maintenance.software"),list:filteredItems3.value},
  {title:t("maintenance.care"),list:filteredItems4.value}
])
const levelList = ref([

])
const typeItem = ref([
  {title:t("maintenance.maintenanceTitle"),},
  {title:t("maintenance.repair"),},
  {title:t("maintenance.replacement"),},
])
const serviceTypeFilter = ref(new Map()
    .set(1,t("maintenance.wearResistantParts"))
    .set(2,t("maintenance.consumableParts"))
    .set(3,t("maintenance.software"))
    .set(4,t("maintenance.care")))
const currencyFilter = ref(new Map().set(1,{title:"人民币",icon:"￥"}).set(2,{title:"Dollar",icon:"$"}))
const currentServiceType = ref(serviceTypeFilter.value.get(1))

const container0 = ref(null)
function handleScroll() {


}
onMounted(() => {
  containers.value = containers.value.map(ref); // Convert refs from template to setup
  window.addEventListener('maintenanceScroll', handleScroll);

  if (locale.value.startsWith('zh')){
    levelList.value =[
      {title:t("maintenance.goldenNodeMaintenance"),price:1500,currency:1},
      {title:t("maintenance.silverNodeMaintenance"),price:2800,currency:1},
      {title:t("maintenance.redCopperNodeMaintenance"),price:4900,currency:1},
    ]
  }else {
    levelList.value =[
      {title:t("maintenance.goldenNodeMaintenance"),price:299,currency:2},
      {title:t("maintenance.silverNodeMaintenance"),price:499,currency:2},
      {title:t("maintenance.redCopperNodeMaintenance"),price:899,currency:2},
    ]
  }

});

onUpdated(() => {

});
</script>

<style scoped>
.container{
  width: 100%;
}

.maintenance-container{
  padding: 48px 0;
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.maintenance-item-container{
  width: 100%;
  max-width: 1200px;
  display: flex;
  flex-direction: column;
}
.maintenance-swiper-container{
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}
.maintenance-parts-name-container{
  width: 19%;
  min-width: 126px;
  background-color: white;
}

.type-drawer-container{
  width: 81%;
  display: flex;
  flex-direction: row;
}

.parts-name-container {
  max-height: 76px;
  width: 100%;
  padding: 16px 5px 32px 0;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: flex-start;
}

.parts-name-container > h1 {
  font-size: 18px;
  font-weight: 500;
  overflow: hidden;
}

.part-item-container{
  width: 100%;
  display: flex;
  flex-direction: column;
}

.first-child .parts-name-container{
  display: none;
}


.part-item{
  min-height: 76px;
  padding: 8px 0;
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}
.name-container{
  padding: 0 8px 0 0;
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
  position: relative;
}
.name-container>p{
  font-size: 16px;
  font-weight: 300;
}

.header-nav{
  z-index: 2;
  position: sticky;
  top: 0px;
  background-color: white;
}

.parts-support-container{
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.type-container{
  min-width: 240px;
  width: calc(100% / 3);
  display: flex;
  flex-direction: row;
  align-items: flex-end;
}

.type-content{
  width: 100%;
  height: 76px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.type-content>h2{
  margin-bottom: 10px;
  font-size: 16px;
  font-weight: 500;
}

.type-item-container{
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}



.maintenance-type-container{
  position: sticky;
  top: 0px;
  height: 76px;
  background-color: white;
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}



.type-item{
  width: calc(100% / 3);
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
}

.type-item>p{
  font-size: 16px;
  opacity: 0.95;
  font-weight: 300;
}


.support-item{
  width: calc(100% / 3);
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  height: 20px;
  padding: 16px 0 32px 0;
}

.support-item>img{
  width: 14px;
}

.desc-container{
  padding: 16px 0;
  width: 100%;
  display: flex;
  flex-direction: column;
}
.desc-container>p{
  margin-top: 8px;
  text-indent: 2em;
  font-size: 16px;
  font-weight: 300;
}
.desc-container>span{
  margin-top: 8px;
  font-size: 14px;
  font-weight: 300;
}
.desc-container>h1{
  text-align: center;
  margin-bottom: 16px;
  font-weight: 500;
  font-size: 28px;
}

@media screen and (max-width: 1232px){
  .maintenance-item-container{
    padding: 0 16px;
  }
  .parts-name-container{
    min-height: 76px;
  }

  .parts-name-container > h1 {
    font-size: 14px;
  }

  .name-container>p{
    font-size: 12px;
  }
  .maintenance-parts-name-container{
  }

  .type-content>h2{
    font-size: 18px;
  }

  .type-item>p{
    font-size: 13px;
  }
}

@media screen and (max-width: 800px){
  .parts-name-container > h1 {
    font-size: 12px;
  }
}

@media screen  and (max-width: 1232px){
  .maintenance-type-container{
    position: sticky;
    top: 0px;
  }
  .type-drawer-container{
    width: 100%;
    display: flex;
    flex-direction: row;
    overflow: auto;
  }
  .type-drawer-container::-webkit-scrollbar {
    width: 0; /* Width of the scrollbar */
    height: 0px;
  }
  .type-drawer-container::-webkit-scrollbar-thumb {
    background-color: transparent; /* Color of the thumb */
  }
  .type-drawer-container::-webkit-scrollbar-track {
    background-color:transparent; /* Color of the track */
  }

  .header-nav{
    position: relative;
    top: 0;
  }

  .type-content>h2{
    font-size: 16px;
  }
  .type-item>p{
    font-size: 12px;
  }

}

@media screen  and (max-width: 480px){
  .type-content>h2{
    font-size: 14px;
  }
  .type-item>p{
    font-size: 10px;
  }
}

</style>
